language: node_js
node_js:
  - '16'
cache:
  npm: false
before_install:
  - git config --global url."https://git@".insteadOf git://
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/" >> .npmrc
branches:
  only:
    - master
deploy:
  provider: script
  edge: true
  cleanup: false
  dpl_version: 2.0.3.beta.4
  script: npm run publish
  on:
    branch: master
