language: node_js
node_js:
  - '12'
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/" >> .npmrc
branches:
  only:
    - master
    - v7.x
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run publish
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run publish -- --allow-earlier-version
    on:
      branch: v7.x
