language: node_js
node_js:
  - '16'
cache:
  npm: false
before_install:
  - git config --global url."https://git@".insteadOf git://
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/" >> .npmrc
branches:
  only:
    - master
deploy:
  provider: script
  edge: true
  cleanup: false
  dpl_version: 2.0.3.beta.4
  script: |
    # Check if main package version changed
    MAIN_VERSION=$(git show HEAD~1:package.json | jq -r '.version')
    CURRENT_VERSION=$(jq -r '.version' package.json)

    echo "Previous main version: $MAIN_VERSION"
    echo "Current main version: $CURRENT_VERSION"

    if [ "$MAIN_VERSION" != "$CURRENT_VERSION" ]; then
      echo "Main package version changed, publishing @fs/eslint-config-frontier-react..."
      npm run publish
    else
      echo "Main package version unchanged, skipping main publish"
    fi

    # Check if shared package exists and has changes
    if [ -d "shared" ]; then
      echo "Shared directory found, checking for shared package changes..."
      SHARED_CHANGED=$(git diff HEAD~1 HEAD --name-only | grep "^shared/" || echo "")
      
      if [ -n "$SHARED_CHANGED" ]; then
        echo "Shared package has changes, publishing @fs/eslint-config-shared..."
        # Copy npm config to shared directory
        cp .npmrc shared/.npmrc
        cd shared && npm run publish
      else
        echo "No changes in shared package, skipping shared publish"
      fi
    fi
  on:
    branch: master
