language: node_js
node_js:
  - '12'
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
  - echo "@fs:registry=https://repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/" >> .npmrc
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on:
    branch: master
