#
# © 2023 by Intellectual Reserve, Inc. All rights reserved.
#

name: frontier-eslint-config-frontier-react
version: "1.1"
builds:
  - name: node-build
    type: build-artifacts
    version: "1"
    operations:
      - name: publish
    properties:
      build_tool: npm
      directory: ./
      runtimes:
        node:
          version: "20"
  - name: code-analysis
    type: code-analysis
    version: "1"
    operations:
      - name: analyze
pipelines:
  - name: master-build-deploy
    type: push-to-master
    version: "1"
    operations:
      - name: start
    properties:
      triggers:
        type: gha
        on:
          push:
            branches: ["master"]
  - name: pr-build
    type: pull-request
    version: "1"
    operations:
      - name: start
    properties:
      triggers:
        type: gha
        on:
          pull_request:
            branches: ["master"]
